# Generated by Django 5.0.7 on 2024-08-09 08:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Email')),
                ('title', models.CharField(max_length=200)),
                ('firstName', models.CharField(max_length=255)),
                ('secondName', models.CharField(max_length=255)),
                ('lastName', models.CharField(max_length=255)),
                ('phoneNumber', models.CharField(max_length=14)),
                ('gender', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('Progect Manager', 'Progectmanager'), ('user', 'User')], default='user', max_length=255)),
                ('archiveReason', models.TextField(blank=True)),
                ('createdBy', models.CharField(max_length=255)),
                ('updatedBy', models.CharField(max_length=255, null=True)),
                ('deletedBy', models.CharField(max_length=255, null=True)),
                ('jobTitle', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=1000)),
                ('isActive', models.BooleanField(default=True)),
                ('archiveReason', models.CharField(max_length=255, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('deletedAt', models.DateTimeField(auto_now=True)),
                ('createdBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projectCreatedBy', to=settings.AUTH_USER_MODEL)),
                ('deletedBy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projectDeletedBy', to=settings.AUTH_USER_MODEL)),
                ('updatedBy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projectUpdatedBy', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('priority', models.CharField(choices=[('High', 'Higth'), ('Medium', 'Medium'), ('Low', 'Low')], max_length=255)),
                ('dueDate', models.DateField(auto_now_add=True, null=True)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Pending', 'Pending'), ('Completed', 'Completed'), ('On Hold', 'Onhold')], default='Open', max_length=80)),
                ('archiveReason', models.CharField(max_length=255, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('deletedAt', models.DateTimeField(auto_now=True)),
                ('assignedId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignedTo', to=settings.AUTH_USER_MODEL)),
                ('createdBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taskCreatedBy', to=settings.AUTH_USER_MODEL)),
                ('deletedBy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='taskDeletedBy', to=settings.AUTH_USER_MODEL)),
                ('projectId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='onProject', to='tms_api.project')),
                ('updatedBy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='taskUpdatedBy', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
